server:
  port: 7001
eureka:
  instance:
    hostname: my-eureka1 #eureka实例的主机名称
  client:
    register-with-eureka: false #不把自己注册到eureka上
    fetch-registry: false #不从eureka上获取服务注册信息,不向消费者一样获取提供者信息
    service-url:
       defaultZone: http://my-eureka2:7002/eureka/,http://my-eureka3:7003/eureka/
#      defaultZone: http://localhost:8761/eureka/







