#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#          exclude: env,beans
server:
  port: 8003
spring:
  application:
    name: pp
eureka:
  client:
    service-url:
      defaultZone: http://my-eureka1:7001/eureka/,http://my-eureka2:7002/eureka/,http://my-eureka3:7003/eureka/
  instance:
      instance-id: service01-pp-8001
      prefer-ip-address: true  #访问路径显示ip

